In [7]:
import numpy as np

In [12]:
A = np.matrix('1 2 3; 4 5 6; 7 8 9')
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
A*=2
A

matrix([[ 4,  8, 12],
        [16, 20, 24],
        [28, 32, 36]])

In [22]:
np.where(A>10, A*0,A)

array([[4, 8, 0],
       [0, 0, 0],
       [0, 0, 0]])