In [2]:
import numpy as np

In [4]:
eye = np.eye(4)
diag = np.matrix([[5,0,0,0],[0,10,0,0],[0,0,15,0],[0,0,0,20]])

print(eye,"\n\n",diag)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]


In [10]:
sum_eye = np.sum(eye)
sum_diag = np.sum(diag)
print('cумма единичной матрицы:', sum_eye, "\nсумма диагональной матрицы:", sum_diag,'\nsum_eye >sum_diag?:',sum_eye < sum_diag)

cумма единичной матрицы: 4.0 
сумма диагональной матрицы: 50 
sum_eye >sum_diag?: True
