In [1]:
import numpy as np

In [18]:
A = np.random.randint(1, 21, size=(3, 3))
B = np.random.randint(1, 21, size=(3, 3))
print(A)
print()
print(B)

[[20 12 14]
 [18 10 11]
 [18 18 16]]

[[20 11 20]
 [ 6 15 19]
 [17 18 11]]


In [14]:
Sum = A+B
Raz = A-B
Umn = A*B

In [26]:
print("Cумма:\n",Sum, "\n")
print("Разность:\n",Raz, "\n")
print("Произведение:\n",Umn, "\n")

Cумма:
 [[28 20 23]
 [ 8 27 22]
 [26  9 11]] 

Разность:
 [[-4 16  9]
 [-2  9  2]
 [12  1  9]] 

Произведение:
 [[192  36 112]
 [ 15 162 120]
 [133  20  10]] 

