In [2]:
import numpy as np

In [7]:
A = np.random.randint(0, 20, size=(2, 3))
B = np.random.randint(0, 20, size=(3, 2))
print(A)
print(B)

[[ 9 10 15]
 [19 11 19]]
[[ 6  2]
 [10 18]
 [13  7]]


In [13]:
print(A.dot(B))

[[349 303]
 [471 369]]
