In [3]:
import numpy as np

In [22]:
A = np.random.randint(1, 21, size=(3, 3))
print("Матрица:\n", A)

Матрица:
 [[10 18 18]
 [ 9 11  7]
 [14 11  7]]


In [19]:
det = np.linalg.det(A)
print("Определитель матрицы:{:.0f}".format(det))

Определитель матрицы:1200


In [11]:
try:
    inverse_matrix = np.linalg.inv(A)
    print("Обратная матрица:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Матрица вырождена и не имеет обратной матрицы.")

Обратная матрица:
 [[-0.145      -0.115       0.215     ]
 [-0.01666667 -0.11666667  0.11666667]
 [ 0.16416667  0.19916667 -0.24916667]]
