In [2]:
import numpy as np

In [4]:
matrix = np.random.randint(1, 51, size=(4, 4))
print("Исходная матрица:\n", matrix)

Исходная матрица:
 [[11 34 24 50]
 [20 33  7 47]
 [13 45 20 27]
 [28 43 12 15]]


In [6]:
transposed_matrix = matrix.T
print("Транспонированная матрица:\n", transposed_matrix)

Транспонированная матрица:
 [[11 20 13 28]
 [34 33 45 43]
 [24  7 20 12]
 [50 47 27 15]]


In [8]:
trace = np.trace(matrix)
print("След матрицы:", trace)

След матрицы: 79
