In [2]:
import numpy as np

In [4]:
A = np.array([[1,1,1],[3,-5,0],[2,0,-5]])
B = np.array([20,0,0])

In [6]:
dA = np.linalg.det(A)
print(dA)

50.000000000000014


In [8]:
Ax = np.copy(A)
Ay = np.copy(A)
Az = np.copy(A)

Ax[:, 0] = B
Ay[:, 1] = B
Az[:, 2] = B

d1 = np.linalg.det(Ax)
d2 = np.linalg.det(Ay)
d3 = np.linalg.det(Az)

print("{} \n\n{} \n{}".format(Ax,Ay,Az))
print("d1={:.0f} \nd2={:.0f} \nd3={:.0f}".format(d1,d2,d3))

[[20  1  1]
 [ 0 -5  0]
 [ 0  0 -5]] 

[[ 1 20  1]
 [ 3  0  0]
 [ 2  0 -5]] 
[[ 1  1 20]
 [ 3 -5  0]
 [ 2  0  0]]
d1=500 
d2=300 
d3=200


In [10]:
x = d1/dA
y = d2/dA
z = d3/dA
print("Ответ\nx={:.0f} \ny={:.0f} \nz={:.0f}".format(x,y,z))

Ответ
x=10 
y=6 
z=4


In [12]:
np.linalg.solve(A,B) #проверка

array([10.,  6.,  4.])